### PR TITLE
added delete all button

### PR DESCRIPTION
**Pull request by eacevedo79**
image

added a button to delete all the videos, it requires an endpoint in selenoid.. sending that pr soon

### CODE REVIEW

**Comment by vania-pooh** [comment]
@eacevedo79 what's the use case? deleting all videos is as easy as deleting all files from the directory.

**Comment by eacevedo79** [comment]
> @eacevedo79 what's the use case? deleting all videos is as easy as deleting all files from the directory.

@vania-pooh 
many users in the company i work for had asked for it, is not always clear to them where the videos are and how to easily delete them without leaving the ui, or in cases where they have no access to the server file system to delete those.

**Comment by vania-pooh** [comment]
@lanwen any ideas?

**Comment by lanwen** [comment]
Its possible to without new endpoint, with the client side loop over the videos. Also maybe better to make multiselect, so that we can select necessary and delete them at once (with option to select all)

**Comment by eacevedo79** [comment]
closing in favor of deleting files manually or with a ui loop/selection

**Pull request closed without merging**
