### PR TITLE
Fixed VNC connect  port when use default port

### PR DESCRIPTION
**Pull request by Dreamacro**
Fixed VNC connect  port when use default port

```js

const link = urlTo("https://github.com")
link.port // ""

```

### CODE REVIEW

**Comment by vania-pooh** [comment]
@Dreamacro thank you for contribution.

**Comment by Dreamacro** [comment]
BTW, What browser and theme is that (referring to the png in the README file)?

**Comment by lanwen** [comment]
Chrome on Mac (was 58+). What kind of theme it should be?

**Comment by Dreamacro** [comment]
@lanwen How to configure Chrome to the effect of png ? 🤣

**Comment by lanwen** [comment]
I use Yandex.Disk software to take screenshots in png and with cool blur effect around window

**Pull request merged**
